// LOCALHOST ### GET http://localhost:3000/contacts ### GET http://localhost:3000/contacts/6362a84a93ae4ea7fbd4fa1f ### GET http://localhost:3000/contacts/6362ba4f6b530a1102f698c2 ### GET http://localhost:3000/contacts/6362ba666b530a1102f698c4
// PRODUCTION Deploy ### GET https://second-back-end-lesson.onrender.com/contacts ### GET https://second-back-end-lesson.onrender.com/contacts/6362a84a93ae4ea7fbd4fa1f ### GET https://second-back-end-lesson.onrender.com/contacts/6362ba4f6b530a1102f698c2 ### GET https://second-back-end-lesson.onrender.com/contacts/6362ba666b530a1102f698c4